parameters:
- name: workspace
  type: string
  default: ci
  
# name: $(TeamProject)_$(Build.DefinitionName)_$(SourceBranchName)_$(Date:yyyyMMdd)$(Rev:.r)
name: $(Date:yyyyMMdd)$(Rev:.r)-$(Build.DefinitionVersion)-$(SourceBranchName)-${{ parameters.workspace }}-$(Build.BuildId)


jobs:
- job: jobA
  displayName: Example Job
  pool:
    name: 'Hosted'
  steps:
  - pwsh: |
      echo "script"
    displayName: Example Task
  