jobs:
- job: ubuntu2004
  pool:
    vmImage: 'ubuntu-20.04'
  steps:
  - bash: |
      echo Hello from Ubuntu 20.04
      lsb_release -d
      ls
      pwd
      ls -la
      echo "hello"
      git status
  - pwsh: |
      Write-Host "`$PSVersionTable.OS"
      $PSVersionTable.OS

- job: buildimage
  pool:
   vmImage: 'ubuntu-20.04'

  steps:
  - task: NodeTool@0
    inputs:
     versionSpec: '8.x'

  - script: |
     npm install
     npm build