trigger: none
schedules:
- cron: '0 1 * * *'
  displayName: 'Nightly build (UTC)'
  always: 'true'
  branches:
    include:
    - main

jobs:
- job: ubuntu2004
  pool:
    vmImage: 'ubuntu-20.04'
  steps:
  - bash: |
      echo Hello from Ubuntu 20.04
      lsb_release -d
  - pwsh: |
      Write-Host "`$PSVersionTable.OS"
      $PSVersionTable.OS
