jobs:
- job: macOS10.15
  pool:
    vmImage: 'macOS-10.15'
  steps:
  - bash: |
      echo hello from macOS Catalina
      sw_vers
- job: macOS11
  pool:
    vmImage: 'macOS-11'
  steps:
  - bash: |
      echo hello from macOS Big Sur
      sw_vers
# - job: macOS12
#   pool:
#     vmImage: 'macOS-12'
#   steps:
#   - bash: |
#       echo hello from macOS Monterey
#       sw_vers
- job: macOSlatest
  pool:
    vmImage: 'macOS-latest'
  steps:
  - bash: |
      echo hello from the latest version of macOS available
      sw_vers